services:
  bootstrap-node:
    build: .
    container_name: bootstrap-node
    environment:
      - NODE_BOOTSTRAP=true
      - NODE_PORT=12137
    ports:
      - "12137:12137"
    stdin_open: true
    tty: true
    networks:
      - onion-network

  config-node:
    build: .
    container_name: config-node
    environment:
      - BOOTSTRAP_HOST=bootstrap-node
      - NODE_PORT=12128
    ports:
      - "12128:12128"
    depends_on:
      - bootstrap-node
    stdin_open: true
    tty: true
    networks:
      - onion-network

  peer:
    build: .
    environment:
      - BOOTSTRAP_HOST=bootstrap-node
    depends_on:
      - bootstrap-node
    stdin_open: true
    tty: true
    networks:
      - onion-network

networks:
  onion-network:
    driver: bridge