services:
  bootstrap-node:
    build: .
    container_name: bootstrap-node
    environment:
      - NODE_BOOTSTRAP=true
      - NODE_PORT=12137
    ports:
      - "12137:12137"
    stdin_open: true
    tty: true
    networks:
      onion-network:
        ipv4_address: 10.12.137.21

  config-node:
    build: .
    container_name: config-node
    environment:
      - BOOTSTRAP_HOST=10.12.137.21
      - NODE_PORT=12128
    ports:
      - "12128:12128"
    depends_on:
      - bootstrap-node
    stdin_open: true
    tty: true
    networks:
      - onion-network

  peer:
    build: .
    environment:
      - BOOTSTRAP_HOST=10.12.137.21
    depends_on:
      - bootstrap-node
    stdin_open: true
    tty: true
    networks:
      - onion-network

networks:
  onion-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.137.0/24
          gateway: 10.12.137.1