package dev.models.enums;

public enum MessageType {
    HANDSHAKE,

    PEER_DISCOVERY_REQUEST, PEER_DISCOVERY_RESPONSE,

    CIRCUIT_CREATE_REQUEST, CIRCUIT_CREATE_RESPONSE, CIRCUIT_EXTEND_REQUEST, CIRCUIT_EXTEND_RESPONSE,

    DATA_TRANSFER_REQUEST, DATA_TRANSFER_RESPONSE,
}
